// Generated by scripts/i18n_build.mjs. Do not edit by hand.
//
// Part of the generated src/ui/i18n.resolved.generated/ directory: one dense
// locale slice per file (each `: EnTranslations` = typeof en, so tsc red-fails a
// missing or renamed key), a back-compat barrel (index.ts) that re-exports every
// slice and assembles the runtime `translations` map, per-locale lazy loaders
// (loaders.ts), and the pending set (pending.ts). Regenerate with
// `npm run i18n:build` (also wired into `npm run build` and `pretest`).
// Reproducibility is checked by tests/i18n_resolved_equivalence.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "es_ES": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "fr_FR": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "fr_CA": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "en_CA": [],
  "it_IT": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "de_DE": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "zh_CN": [],
  "zh_TW": [],
  "ko_KR": [],
  "ja_JP": [],
  "pt_BR": [
    "hudChrome.landing.highContrast",
    "hudChrome.landing.highContrastAria",
    "hudChrome.options.highContrastBackground",
    "hudChrome.options.uiScale"
  ],
  "ru_RU": []
};
