import type { MobTemplate } from '../../types';

export const DELVE_MOBS: Record<string, MobTemplate> = {
  // --- Trash ---
  reliquary_ledger_wraith: {
    id: 'reliquary_ledger_wraith',
    name: 'Ledger Wraith',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 30,
    hpPerLevel: 10,
    dmgBase: 4,
    dmgPerLevel: 1.3,
    attackSpeed: 1.9,
    armorPerLevel: 5,
    moveSpeed: 7.5,
    aggroRadius: 16,
    // Stacks corrode fast due to quick attacks; fragile once reached
    corrode: { chance: 0.45, armor: 6, maxStacks: 4, duration: 12, name: 'Ledger Rot' },
    loot: [{ copper: 6, chance: 1 }],
    scale: 0.85,
    color: 0x9ba8a0,
  },
  reliquary_funeral_ringer: {
    id: 'reliquary_funeral_ringer',
    name: 'Funeral Ringer',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 38,
    hpPerLevel: 13,
    dmgBase: 5,
    dmgPerLevel: 1.5,
    attackSpeed: 2.3,
    armorPerLevel: 8,
    moveSpeed: 6,
    aggroRadius: 11,
    // Periodic AoE chime; when killed it empowers nearby Ringers, mind kill order
    aoePulse: { min: 5, max: 9, radius: 6, every: 4, name: 'Funeral Chime' },
    packFrenzy: { radius: 10, hasteMult: 1.3, duration: 6 },
    loot: [{ copper: 8, chance: 1 }],
    scale: 1.0,
    color: 0x8a8070,
  },
  reliquary_gravecall_acolyte: {
    id: 'reliquary_gravecall_acolyte',
    name: 'Gravecall Acolyte',
    minLevel: 7,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 42,
    hpPerLevel: 14,
    dmgBase: 5,
    dmgPerLevel: 1.4,
    attackSpeed: 2.5,
    armorPerLevel: 7,
    moveSpeed: 7,
    aggroRadius: 10,
    // Healing received cut 35% per hit, kills Tessa's effectiveness if ignored
    mortalStrike: { chance: 0.4, healReduction: 0.35, duration: 8, name: 'Grave Hex' },
    loot: [{ copper: 10, chance: 1 }],
    scale: 1.0,
    color: 0x4a3828,
  },
  // Weak undead add summoned by the `restless_graves` Heroic affix a few seconds
  // after a piece of trash dies. Deliberately frail, it's bonus pressure, not a
  // planned pull. (Do not reuse the lvl-18 dungeon `raised_bonewalker`.)
  reliquary_bonewalker: {
    id: 'reliquary_bonewalker',
    name: 'Raised Bonewalker',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 20,
    hpPerLevel: 7,
    dmgBase: 3,
    dmgPerLevel: 1.1,
    attackSpeed: 2.2,
    armorPerLevel: 4,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [{ copper: 3, chance: 1 }],
    scale: 0.8,
    color: 0xb9b2a4,
  },
  reliquary_saintless_effigy: {
    id: 'reliquary_saintless_effigy',
    name: 'Saintless Effigy',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    ccImmune: true,
    hpBase: 72,
    hpPerLevel: 24,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.9,
    armorPerLevel: 18,
    moveSpeed: 5,
    aggroRadius: 9,
    // Slow, can't be CC'd, cleaves anyone standing adjacent, tank it solo
    cleave: { radius: 3.5, mult: 0.6, name: 'Stone Sweep' },
    loot: [{ copper: 60, chance: 1 }],
    scale: 1.25,
    color: 0xc8beb0,
  },

  // --- Boss ---
  deacon_varric: {
    id: 'deacon_varric',
    name: 'Deacon Varric',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    boss: true,
    hpBase: 100,
    hpPerLevel: 22,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 14,
    stomp: { radius: 8, every: 12, duration: 1.5, min: 14, max: 22, name: 'Bell Toll' },
    summonAdds: { mobId: 'reliquary_funeral_ringer', count: 2, atHpPct: [0.6, 0.3] },
    enrage: { belowHpPct: 0.2, dmgMult: 1.4, hasteMult: 1.2 },
    loot: [{ copper: 320, chance: 1 }],
    scale: 1.6,
    color: 0x7b7d7d,
  },

  // --- Companion (friendly, no loot) ---
  acolyte_tessa: {
    id: 'acolyte_tessa',
    name: 'Acolyte Tessa',
    minLevel: 8,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 55,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.2,
    attackSpeed: 2.6,
    armorPerLevel: 8,
    moveSpeed: 7,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xebedef,
  },
};
