import type { MobTemplate } from '../../types';

export const DELVE_MOBS: Record<string, MobTemplate> = {
  // --- Trash ---
  reliquary_ledger_wraith: {
    id: 'reliquary_ledger_wraith',
    name: 'Ledger Wraith',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 30,
    hpPerLevel: 10,
    dmgBase: 4,
    dmgPerLevel: 1.3,
    attackSpeed: 1.9,
    armorPerLevel: 5,
    moveSpeed: 7.5,
    aggroRadius: 16,
    // Stacks corrode fast due to quick attacks; fragile once reached
    corrode: { chance: 0.45, armor: 6, maxStacks: 4, duration: 12, name: 'Ledger Rot' },
    loot: [{ copper: 6, chance: 1 }],
    scale: 0.85,
    color: 0x9ba8a0,
  },
  reliquary_funeral_ringer: {
    id: 'reliquary_funeral_ringer',
    name: 'Funeral Ringer',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 38,
    hpPerLevel: 13,
    dmgBase: 5,
    dmgPerLevel: 1.5,
    attackSpeed: 2.3,
    armorPerLevel: 8,
    moveSpeed: 6,
    aggroRadius: 11,
    // Periodic AoE chime; when killed it empowers nearby Ringers, mind kill order
    aoePulse: { min: 5, max: 9, radius: 6, every: 4, name: 'Funeral Chime' },
    packFrenzy: { radius: 10, hasteMult: 1.3, duration: 6 },
    loot: [{ copper: 8, chance: 1 }],
    scale: 1.0,
    color: 0x8a8070,
  },
  reliquary_gravecall_acolyte: {
    id: 'reliquary_gravecall_acolyte',
    name: 'Gravecall Acolyte',
    minLevel: 7,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 42,
    hpPerLevel: 14,
    dmgBase: 5,
    dmgPerLevel: 1.4,
    attackSpeed: 2.5,
    armorPerLevel: 7,
    moveSpeed: 7,
    aggroRadius: 10,
    // Healing received cut 35% per hit, kills Tessa's effectiveness if ignored
    mortalStrike: { chance: 0.4, healReduction: 0.35, duration: 8, name: 'Grave Hex' },
    loot: [{ copper: 10, chance: 1 }],
    scale: 1.0,
    color: 0x4a3828,
  },
  // Weak undead add summoned by the `restless_graves` Heroic affix a few seconds
  // after a piece of trash dies. Deliberately frail, it's bonus pressure, not a
  // planned pull. (Do not reuse the lvl-18 dungeon `raised_bonewalker`.)
  reliquary_bonewalker: {
    id: 'reliquary_bonewalker',
    name: 'Raised Bonewalker',
    minLevel: 7,
    maxLevel: 8,
    family: 'undead',
    hpBase: 20,
    hpPerLevel: 7,
    dmgBase: 3,
    dmgPerLevel: 1.1,
    attackSpeed: 2.2,
    armorPerLevel: 4,
    moveSpeed: 7,
    aggroRadius: 12,
    loot: [{ copper: 3, chance: 1 }],
    scale: 0.8,
    color: 0xb9b2a4,
  },
  reliquary_saintless_effigy: {
    id: 'reliquary_saintless_effigy',
    name: 'Saintless Effigy',
    minLevel: 8,
    maxLevel: 8,
    family: 'undead',
    elite: true,
    ccImmune: true,
    hpBase: 72,
    hpPerLevel: 24,
    dmgBase: 10,
    dmgPerLevel: 2.5,
    attackSpeed: 2.9,
    armorPerLevel: 18,
    moveSpeed: 5,
    aggroRadius: 9,
    // Slow, can't be CC'd, cleaves anyone standing adjacent, tank it solo
    cleave: { radius: 3.5, mult: 0.6, name: 'Stone Sweep' },
    loot: [{ copper: 60, chance: 1 }],
    scale: 1.25,
    color: 0xc8beb0,
  },

  // --- Boss ---
  deacon_varric: {
    id: 'deacon_varric',
    name: 'Deacon Varric',
    minLevel: 9,
    maxLevel: 9,
    family: 'undead',
    elite: true,
    boss: true,
    hpBase: 100,
    hpPerLevel: 22,
    dmgBase: 8,
    dmgPerLevel: 2.4,
    attackSpeed: 2.2,
    armorPerLevel: 20,
    moveSpeed: 7,
    aggroRadius: 14,
    stomp: { radius: 8, every: 12, duration: 1.5, min: 14, max: 22, name: 'Bell Toll' },
    summonAdds: { mobId: 'reliquary_funeral_ringer', count: 2, atHpPct: [0.6, 0.3] },
    enrage: { belowHpPct: 0.2, dmgMult: 1.4, hasteMult: 1.2 },
    loot: [{ copper: 320, chance: 1 }],
    scale: 1.6,
    color: 0x7b7d7d,
  },

  // --- Drowned Litany trash ---
  deepfen_spearjaw: {
    id: 'deepfen_spearjaw',
    name: 'Deepfen Spearjaw',
    minLevel: 12,
    maxLevel: 13,
    family: 'beast',
    hpBase: 58,
    hpPerLevel: 18,
    dmgBase: 8,
    dmgPerLevel: 2.1,
    attackSpeed: 2.0,
    armorPerLevel: 9,
    moveSpeed: 8,
    aggroRadius: 15,
    canSwim: true,
    // Quick amphibious skirmisher, bleeds on repeated hits
    corrode: { chance: 0.35, armor: 5, maxStacks: 3, duration: 10, name: 'Spearjaw Gash' },
    loot: [{ copper: 9, chance: 1 }],
    scale: 1.05,
    color: 0x3d5a4a,
  },
  mirefen_widowling: {
    id: 'mirefen_widowling',
    name: 'Mirefen Widowling',
    minLevel: 12,
    maxLevel: 13,
    family: 'beast',
    hpBase: 34,
    hpPerLevel: 11,
    dmgBase: 5,
    dmgPerLevel: 1.4,
    attackSpeed: 1.8,
    armorPerLevel: 5,
    moveSpeed: 7.5,
    aggroRadius: 12,
    // Swarming venom-spider, low hp, high uptime, poison stacks
    mortalStrike: { chance: 0.3, healReduction: 0.25, duration: 8, name: 'Widow Venom' },
    loot: [{ copper: 5, chance: 1 }],
    scale: 0.75,
    color: 0x2a1f2e,
  },
  reedbound_acolyte: {
    id: 'reedbound_acolyte',
    name: 'Reedbound Acolyte',
    minLevel: 12,
    maxLevel: 13,
    family: 'humanoid',
    hpBase: 40,
    hpPerLevel: 13,
    dmgBase: 6,
    dmgPerLevel: 1.6,
    attackSpeed: 2.4,
    armorPerLevel: 6,
    moveSpeed: 7,
    aggroRadius: 16,
    // Ranged debuffer, cuts healing received like Gravecall Acolyte's Grave Hex
    mortalStrike: { chance: 0.4, healReduction: 0.35, duration: 8, name: 'Reed Hex' },
    loot: [{ copper: 9, chance: 1 }],
    scale: 0.95,
    color: 0x5c6b3c,
  },
  drowned_cantor: {
    id: 'drowned_cantor',
    name: 'Drowned Cantor',
    minLevel: 12,
    maxLevel: 13,
    family: 'undead',
    hpBase: 44,
    hpPerLevel: 15,
    dmgBase: 5,
    dmgPerLevel: 1.3,
    attackSpeed: 2.3,
    armorPerLevel: 7,
    moveSpeed: 6.5,
    aggroRadius: 11,
    // Support caster, mends nearby drowned adds
    mendAlly: { healMin: 6, healMax: 10, radius: 8, every: 6, name: 'Cantor Hymn' },
    loot: [{ copper: 10, chance: 1 }],
    scale: 1.0,
    color: 0x7a8a9a,
  },
  grave_silt_bulwark: {
    id: 'grave_silt_bulwark',
    name: 'Grave Silt Bulwark',
    minLevel: 12,
    maxLevel: 13,
    family: 'undead',
    elite: true,
    hpBase: 70,
    hpPerLevel: 23,
    dmgBase: 9,
    dmgPerLevel: 2.3,
    attackSpeed: 2.8,
    armorPerLevel: 16,
    moveSpeed: 5.5,
    aggroRadius: 9,
    // Slow anchor tank, cleaves anyone adjacent like the Saintless Effigy
    cleave: { radius: 3.5, mult: 0.55, name: 'Silt Sweep' },
    loot: [{ copper: 55, chance: 1 }],
    scale: 1.2,
    color: 0x4a4438,
  },
  choir_thrall: {
    id: 'choir_thrall',
    name: 'Choir Thrall',
    minLevel: 12,
    maxLevel: 14,
    family: 'undead',
    hpBase: 22,
    hpPerLevel: 8,
    dmgBase: 4,
    dmgPerLevel: 1.2,
    attackSpeed: 2.1,
    armorPerLevel: 4,
    moveSpeed: 7,
    aggroRadius: 12,
    // Weak add, spawns in waves and from Sister Nhalia's boss adds/Final Bell
    loot: [{ copper: 3, chance: 1 }],
    scale: 0.85,
    color: 0xb3aca0,
  },
  sump_troll_devourer: {
    id: 'sump_troll_devourer',
    name: 'Sump Troll Devourer',
    minLevel: 13,
    maxLevel: 14,
    family: 'beast',
    elite: true,
    ccImmune: true,
    hpBase: 90,
    hpPerLevel: 28,
    dmgBase: 12,
    dmgPerLevel: 2.8,
    attackSpeed: 2.6,
    armorPerLevel: 18,
    moveSpeed: 6,
    aggroRadius: 13,
    canSwim: true,
    // Guarded elite over the water, can't be CC'd, punishes anyone lingering
    stomp: { radius: 7, every: 11, duration: 1.5, min: 16, max: 24, name: 'Sump Slam' },
    enrage: { belowHpPct: 0.25, dmgMult: 1.35, hasteMult: 1.15 },
    loot: [{ copper: 70, chance: 1 }],
    scale: 1.5,
    color: 0x54634a,
  },
  spider_egg_sac: {
    id: 'spider_egg_sac',
    name: 'Spider Egg-Sac',
    minLevel: 12,
    maxLevel: 13,
    family: 'beast',
    hpBase: 1,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 3,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    // Stationary destroyable prop, 1hp on purpose: bursts into widowling adds
    // on death (onEggSacBurst in drowned_litany_rooms.ts), never fights back.
    loot: [],
    scale: 0.9,
    color: 0x8a7a5a,
  },

  // --- Drowned Litany boss ---
  sister_nhalia_drowned_canticle: {
    id: 'sister_nhalia_drowned_canticle',
    name: 'Sister Nhalia',
    minLevel: 15,
    maxLevel: 15,
    family: 'undead',
    elite: true,
    boss: true,
    ccImmune: true,
    hpBase: 150,
    hpPerLevel: 30,
    dmgBase: 11,
    dmgPerLevel: 2.9,
    attackSpeed: 2.3,
    armorPerLevel: 24,
    moveSpeed: 7,
    aggroRadius: 16,
    loot: [{ copper: 420, chance: 1 }],
    scale: 1.65,
    color: 0x3a5a68,
  },

  // --- Drowned Litany driver-only projectile (no AI, no loot, no XP) ---
  tolling_bell: {
    id: 'tolling_bell',
    name: 'Tolling Bell',
    minLevel: 15,
    maxLevel: 15,
    family: 'undead',
    hpBase: 1,
    hpPerLevel: 0,
    dmgBase: 0,
    dmgPerLevel: 0,
    attackSpeed: 3,
    armorPerLevel: 0,
    moveSpeed: 0,
    aggroRadius: 0,
    loot: [],
    scale: 0.6,
    color: 0xddbbff,
  },

  // --- Companion (friendly, no loot) ---
  acolyte_tessa: {
    id: 'acolyte_tessa',
    name: 'Acolyte Tessa',
    minLevel: 8,
    maxLevel: 8,
    family: 'humanoid',
    hpBase: 55,
    hpPerLevel: 16,
    dmgBase: 4,
    dmgPerLevel: 1.2,
    attackSpeed: 2.6,
    armorPerLevel: 8,
    moveSpeed: 7,
    aggroRadius: 0,
    loot: [],
    scale: 1.0,
    color: 0xebedef,
  },
};
