// Generates src/guide/content.generated.ts from the sim source of truth (CLASSES +
// TALENTS), so the Guide's class data never drifts from the game. Mirrors the
// esbuild-bundle pattern in scripts/export_loot_spreadsheet.mjs (never import raw .ts).
// Run via `npm run wiki:content`; the build runs it and the committed output is
// freshness-checked in tests/guide.test.ts. Deterministic: reads data, writes a file.
import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const outFile = path.join(root, 'src', 'guide', 'content.generated.ts');

const entrySource = `
  export { CLASSES, ABILITIES } from './src/sim/content/classes.ts';
  export { TALENTS } from './src/sim/content/talents.ts';
  export { ALL_CLASSES } from './src/sim/types.ts';
  export { ZONES } from './src/sim/data.ts';
  export { ZONE1_MOBS } from './src/sim/content/zone1.ts';
  export { ZONE2_MOBS } from './src/sim/content/zone2.ts';
  export { ZONE3_MOBS } from './src/sim/content/zone3.ts';
`;

const built = await esbuild.build({
  stdin: { contents: entrySource, resolveDir: root, sourcefile: 'wiki-content-entry.ts', loader: 'ts' },
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const dataUrl = `data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`;
const { CLASSES, ABILITIES, TALENTS, ALL_CLASSES, ZONES, ZONE1_MOBS, ZONE2_MOBS, ZONE3_MOBS } = await import(dataUrl);

const ROLE_ORDER = ['tank', 'healer', 'dps'];
const hex = (n) => `#${(n >>> 0).toString(16).padStart(6, '0').slice(-6)}`;

// How many early, spoiler-safe abilities to surface as the "signature kit".
const SIGNATURE_COUNT = 6;

const classes = ALL_CLASSES.map((id) => {
  const def = CLASSES[id];
  const specs = (TALENTS[id]?.specs ?? []).map((s) => ({ name: s.name, role: s.role }));
  const roles = ROLE_ORDER.filter((r) => specs.some((s) => s.role === r));
  const signatureAbilities = (def.abilities ?? [])
    .slice(0, SIGNATURE_COUNT)
    .map((aid) => ({ id: aid, name: ABILITIES[aid]?.name ?? aid }));
  return { id, color: hex(def.color), resource: def.resourceType, roles, specs, signatureAbilities };
});

// Zones, in world order (south to north).
const zones = ZONES.map((z) => ({
  id: z.id,
  name: z.name,
  min: z.levelRange[0],
  max: z.levelRange[1],
  biome: z.biome,
  hub: z.hub?.name ?? '',
}));

// Bestiary: OVERWORLD creatures only, grouped by family. Excludes elite/boss (dungeon
// and raid encounters) and warlock pet summons, so nothing here spoils instanced content.
const FAMILY_ORDER = ['beast', 'spider', 'murloc', 'kobold', 'humanoid', 'troll', 'ogre', 'undead', 'elemental', 'dragonkin'];
const famMap = {};
for (const [id, m] of Object.entries({ ...ZONE1_MOBS, ...ZONE2_MOBS, ...ZONE3_MOBS })) {
  if (m.elite || m.boss) continue;
  if (id.startsWith('warlock_')) continue; // summoned pets, not wild creatures
  if (/vision/i.test(id) || /^Vision\b/.test(m.name)) continue; // cinematic apparitions, not creatures
  (famMap[m.family] ??= new Map()).set(m.name, { name: m.name, min: m.minLevel, max: m.maxLevel, rare: !!m.rare });
}
const families = FAMILY_ORDER
  .filter((f) => famMap[f])
  .map((f) => ({
    family: f,
    creatures: [...famMap[f].values()].sort((a, b) => a.min - b.min || a.name.localeCompare(b.name)),
  }));

const header = `// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with \`npm run wiki:content\`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideClassSpec { name: string; role: GuideRole; }
export interface GuideSignatureAbility { id: string; name: string; }

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideSignatureAbility[];
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
}

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }
`;

writeFileSync(outFile, [
  header,
  `\nexport const GUIDE_CLASSES: GuideClassInfo[] = ${JSON.stringify(classes, null, 2)};\n`,
  `\nexport const GUIDE_ZONES: GuideZoneInfo[] = ${JSON.stringify(zones, null, 2)};\n`,
  `\nexport const GUIDE_FAMILIES: GuideFamily[] = ${JSON.stringify(families, null, 2)};\n`,
].join(''));
// eslint-disable-next-line no-console
console.log(`generated src/guide/content.generated.ts (${classes.length} classes, ${zones.length} zones, ${families.length} families)`);
