// Generated by scripts/i18n_admin_build.mjs. Do not edit by hand.
//
// Part of the generated src/admin/i18n.resolved.generated/ directory: one dense
// ADMIN locale slice per file (each `: AdminTranslations` = typeof en, so tsc
// red-fails a missing or renamed key), a back-compat barrel (index.ts) that
// re-exports every slice and assembles the runtime `translations` map, per-locale
// loaders (loaders.ts, parity scaffolding - admin is NOT lazy), and the pending
// set (pending.ts). The admin SPA consumes ONLY this table (never the game locale
// table); regenerate with `npm run i18n:admin` (also wired into `npm run build`
// and `pretest`). Reproducibility is checked by tests/i18n_admin_catalog.test.ts.

export const pending: Record<string, readonly string[]> = {
  "es": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "es_ES": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "fr_FR": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "fr_CA": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "en_CA": [],
  "it_IT": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "de_DE": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "zh_CN": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "zh_TW": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "ko_KR": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "ja_JP": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "pt_BR": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ],
  "ru_RU": [
    "charts.onlineHistory",
    "charts.onlineTooltip",
    "charts.range.24h",
    "charts.range.30d",
    "charts.range.7d",
    "stats.activeAccounts30d",
    "stats.activeAccounts7d",
    "stats.avgPlaytimePerAccount",
    "stats.onlineAccounts",
    "stats.peakOnlineAllTime",
    "stats.peakOnlineToday",
    "stats.returningAccounts24h",
    "stats.siteUsersNow"
  ]
};
