#!/usr/bin/env node
// One-shot helper to rebuild src/game/sfx_manifest.generated.ts from existing
// on-disk clips. Mirrors the manifest portion of scripts/gen_sfx.mjs (no API
// calls) so we can extend the SfxEntry shape -> { url, loop, variants? } in a
// PR that does NOT require re-running the ElevenLabs clip generator.
//
// Usage: node scripts/_rebuild_sfx_manifest_from_disk.mjs
//
// Idempotent and side-effect-free other than the file write. Safe to run from
// a worktree; never deletes audio it does not own.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { SFX } from './sfx/sfx_prompts.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const sfxDir = path.join(root, 'public/audio/sfx');
const manifestPath = path.join(root, 'src/game/sfx_manifest.generated.ts');

function takeCount(entry) {
  const n = Number.isFinite(entry.takes) ? Math.max(1, Math.floor(entry.takes)) : 1;
  return Math.min(n, 16);
}
function clipPath(key, take) {
  return path.join(sfxDir, take === 1 ? `${key}.mp3` : `${key}_${take}.mp3`);
}
function clipUrl(key, take) {
  return take === 1 ? `/audio/sfx/${key}.mp3` : `/audio/sfx/${key}_${take}.mp3`;
}

const entries = {};
let variantEntries = 0;
for (const entry of SFX) {
  const total = takeCount(entry);
  const urls = [];
  let haveAny = false;
  for (let take = 1; take <= total; take++) {
    if (existsSync(clipPath(entry.key, take))) {
      urls.push(clipUrl(entry.key, take));
      haveAny = true;
    }
  }
  if (!haveAny) continue;
  const [first, ...rest] = urls;
  const record = { url: first, loop: !!entry.loop };
  if (rest.length > 0) {
    record.variants = rest;
    variantEntries++;
  }
  entries[entry.key] = record;
}
const sorted = Object.fromEntries(
  Object.keys(entries)
    .sort()
    .map((k) => [k, entries[k]]),
);
mkdirSync(path.dirname(manifestPath), { recursive: true });
writeFileSync(
  manifestPath,
  [
    '// Generated by scripts/gen_sfx.mjs. Do not edit by hand.',
    '// Maps a sound-effect key to its public audio path and loop flag. Entries',
    '// with multiple takes carry `variants?: string[]` listing the URLs of takes',
    '// 2..N; the runtime Rng-weighted picker in src/game/sfx.ts selects one of',
    '// [url, ...variants] per play with a no-repeat bias.',
    'export interface SfxEntry { url: string; loop: boolean; variants?: string[] }',
    'export const SFX_CLIPS: Record<string, SfxEntry> =',
    `${JSON.stringify(sorted, null, 2)} as const;`,
    '',
  ].join('\n'),
);
console.log(
  `wrote ${path.relative(root, manifestPath)}: ${Object.keys(sorted).length} entries, ${variantEntries} with variants`,
);
