// Generates src/editor/asset_catalog.generated.ts: the map editor's placement
// asset id -> GLB path catalogue. Scans public/models/<category>/**/*.glb for
// the categories the asset browser (src/editor/asset_browser.ts) renders tabs
// for. Run via `npm run editor:catalog`; also wired into `build`/`pretest` so
// the catalogue tracks public/models without a manual step, same pattern as
// scripts/build_media_manifest.mjs.

import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const modelsDir = path.join(root, 'public/models');
const generatedPath = path.join(root, 'src/editor/asset_catalog.generated.ts');

// Alphabetical, matching src/editor/asset_browser.ts's CATEGORY_KEYS. Deliberately
// excludes public/models/armor: those GLBs are worn-equipment variants for player
// character rigs, not standalone placeable decoration.
const CATEGORIES = [
  'biome',
  'chars',
  'creatures',
  'dungeon',
  'foliage',
  'props',
  'quest',
  'resources',
  'tools',
  'weapons',
];

function walkGlbs(dir) {
  const out = [];
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, ent.name);
    if (ent.isDirectory()) out.push(...walkGlbs(p));
    else if (ent.isFile() && ent.name.toLowerCase().endsWith('.glb')) out.push(p);
  }
  return out;
}

function humanize(name) {
  return name
    .replace(/[_-]+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(' ');
}

function catalogEntries() {
  const entries = [];
  for (const category of CATEGORIES) {
    const dir = path.join(modelsDir, category);
    if (!existsSync(dir) || !statSync(dir).isDirectory()) continue;
    const files = walkGlbs(dir).sort();
    for (const file of files) {
      const relFromCategory = path.relative(dir, file).split(path.sep).join('/');
      const relNoExt = relFromCategory.slice(0, -'.glb'.length);
      const id = `${category}/${relNoExt}`;
      const label = humanize(path.posix.basename(relNoExt));
      const relFromPublic = path
        .relative(path.join(root, 'public'), file)
        .split(path.sep)
        .join('/');
      entries.push({ id, label, category, path: `/${relFromPublic}` });
    }
  }
  return entries;
}

function generate() {
  const entries = catalogEntries();
  mkdirSync(path.dirname(generatedPath), { recursive: true });
  const lines = [
    '// Generated by scripts/build_editor_asset_catalog.mjs. Do not edit by hand.',
    '',
    'export interface AssetCatalogEntry {',
    '  id: string;',
    '  label: string;',
    '  category: string;',
    '  path: string;',
    '}',
    '',
    `export const ASSET_CATEGORIES: readonly string[] = ${JSON.stringify(CATEGORIES)} as const;`,
    '',
    'export const ASSET_CATALOG: readonly AssetCatalogEntry[] = ',
    `${JSON.stringify(entries, null, 2)} as const;`,
    '',
    'const BY_ID: ReadonlyMap<string, AssetCatalogEntry> = new Map(',
    '  ASSET_CATALOG.map((entry) => [entry.id, entry]),',
    ');',
    '',
    'export function assetById(id: string): AssetCatalogEntry | undefined {',
    '  return BY_ID.get(id);',
    '}',
    '',
  ];
  writeFileSync(generatedPath, lines.join('\n'));
  console.log(
    `generated ${path.relative(root, generatedPath)} (${entries.length} placeable assets across ${CATEGORIES.length} categories)`,
  );
}

generate();
