// WARFARE gear sold by Bramble, the Honor Quartermaster. Every item is a
// level-20 epic sourced at level 22, so the item-level index would read it as
// item level 28 after the epic +6 quality bump -- EXCEPT this fork's equipment
// model has no neck or ring slot (see src/sim/types.ts EquipSlot), so unlike
// upstream's 40-piece kit this catalog covers only the 8 slots the fork
// actually has: one full armor kit per stat profile (mail-str, mail-caster,
// leather, cloth) plus one mainhand per profile, 31 items total. Primary stat
// sums exactly match the slot budgets in item_budget.ts; WARFARE ratings
// mirror those same slot budgets (see docs/design/warfare.md).

import type { ItemDef, NpcDef } from '../types';

export const FURY_NPC_ID = 'bramble';
// Reserved so adding Bramble does not shift the deterministic nextId sequence
// used by every existing world spawn and parity replay.
export const FURY_ENTITY_ID = 1_000_000_001;
export const WARFARE_SOURCE_LEVEL = 22;

export const WARFARE_ITEMS: Record<string, ItemDef> = {
  // Bramblewar Battlegear: Strength and Stamina mail.
  bramblewar_warhelm: {
    id: 'bramblewar_warhelm',
    name: 'Bramblewar Warhelm',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 265, str: 7, sta: 10 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_warspaulders: {
    id: 'bramblewar_warspaulders',
    name: 'Bramblewar Warspaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 220, str: 6, sta: 9 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_warplate: {
    id: 'bramblewar_warplate',
    name: 'Bramblewar Warplate',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 305, str: 9, sta: 11 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_girdle: {
    id: 'bramblewar_girdle',
    name: 'Bramblewar Girdle',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, str: 6, sta: 8 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_legguards: {
    id: 'bramblewar_legguards',
    name: 'Bramblewar Legguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 285, str: 8, sta: 10 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_gauntlets: {
    id: 'bramblewar_gauntlets',
    name: 'Bramblewar Gauntlets',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, str: 6, sta: 8 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  bramblewar_sabatons: {
    id: 'bramblewar_sabatons',
    name: 'Bramblewar Sabatons',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 190, str: 6, sta: 7 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Thornbound Vestments: Intellect, Stamina, and Spirit mail.
  thornbound_crown: {
    id: 'thornbound_crown',
    name: 'Thornbound Crown',
    kind: 'armor',
    armorType: 'mail',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 265, int: 8, sta: 6, spi: 3 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_spaulders: {
    id: 'thornbound_spaulders',
    name: 'Thornbound Spaulders',
    kind: 'armor',
    armorType: 'mail',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 220, int: 7, sta: 5, spi: 3 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_hauberk: {
    id: 'thornbound_hauberk',
    name: 'Thornbound Hauberk',
    kind: 'armor',
    armorType: 'mail',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 305, int: 9, sta: 7, spi: 4 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_waistguard: {
    id: 'thornbound_waistguard',
    name: 'Thornbound Waistguard',
    kind: 'armor',
    armorType: 'mail',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_legmail: {
    id: 'thornbound_legmail',
    name: 'Thornbound Legmail',
    kind: 'armor',
    armorType: 'mail',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 285, int: 8, sta: 6, spi: 4 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_handguards: {
    id: 'thornbound_handguards',
    name: 'Thornbound Handguards',
    kind: 'armor',
    armorType: 'mail',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 200, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  thornbound_greaves: {
    id: 'thornbound_greaves',
    name: 'Thornbound Greaves',
    kind: 'armor',
    armorType: 'mail',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 190, int: 6, sta: 4, spi: 3 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Nettlestalker Kit: Agility and Stamina leather.
  nettlestalker_cowl: {
    id: 'nettlestalker_cowl',
    name: 'Nettlestalker Cowl',
    kind: 'armor',
    armorType: 'leather',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 150, agi: 8, sta: 9 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_shoulderguards: {
    id: 'nettlestalker_shoulderguards',
    name: 'Nettlestalker Shoulderguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 135, agi: 7, sta: 8 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_harness: {
    id: 'nettlestalker_harness',
    name: 'Nettlestalker Harness',
    kind: 'armor',
    armorType: 'leather',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 155, agi: 9, sta: 11 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_waistband: {
    id: 'nettlestalker_waistband',
    name: 'Nettlestalker Waistband',
    kind: 'armor',
    armorType: 'leather',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 90, agi: 6, sta: 8 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_legguards: {
    id: 'nettlestalker_legguards',
    name: 'Nettlestalker Legguards',
    kind: 'armor',
    armorType: 'leather',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 120, agi: 8, sta: 10 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_grips: {
    id: 'nettlestalker_grips',
    name: 'Nettlestalker Grips',
    kind: 'armor',
    armorType: 'leather',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 95, agi: 6, sta: 8 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  nettlestalker_treads: {
    id: 'nettlestalker_treads',
    name: 'Nettlestalker Treads',
    kind: 'armor',
    armorType: 'leather',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 85, agi: 6, sta: 7 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Mossweave Regalia: Intellect, Stamina, and Spirit cloth.
  mossweave_cowl: {
    id: 'mossweave_cowl',
    name: 'Mossweave Cowl',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'helmet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 70, int: 8, sta: 6, spi: 3 },
    pvpOffenseRating: 17,
    pvpDefenseRating: 17,
    priceHonor: 500,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_mantle: {
    id: 'mossweave_mantle',
    name: 'Mossweave Mantle',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'shoulder',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 50, int: 7, sta: 5, spi: 3 },
    pvpOffenseRating: 15,
    pvpDefenseRating: 15,
    priceHonor: 400,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_raiment: {
    id: 'mossweave_raiment',
    name: 'Mossweave Raiment',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'chest',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 80, int: 9, sta: 7, spi: 4 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 700,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_cord: {
    id: 'mossweave_cord',
    name: 'Mossweave Cord',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'waist',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 45, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 250,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_legwraps: {
    id: 'mossweave_legwraps',
    name: 'Mossweave Legwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'legs',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 65, int: 8, sta: 6, spi: 4 },
    pvpOffenseRating: 18,
    pvpDefenseRating: 18,
    priceHonor: 600,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_handwraps: {
    id: 'mossweave_handwraps',
    name: 'Mossweave Handwraps',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'gloves',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 45, int: 6, sta: 5, spi: 3 },
    pvpOffenseRating: 14,
    pvpDefenseRating: 14,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },
  mossweave_slippers: {
    id: 'mossweave_slippers',
    name: 'Mossweave Slippers',
    kind: 'armor',
    armorType: 'cloth',
    slot: 'feet',
    quality: 'epic',
    requiredLevel: 20,
    stats: { armor: 40, int: 6, sta: 4, spi: 3 },
    pvpOffenseRating: 13,
    pvpDefenseRating: 13,
    priceHonor: 300,
    sellValue: 0,
    soulbound: true,
  },

  // Main hands: Strength, Agility, and caster profiles on the ilvl-28 DPS curve.
  last_bloom_greatblade: {
    id: 'last_bloom_greatblade',
    name: 'Last Bloom Greatblade',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 34, max: 50, speed: 2.8 },
    stats: { str: 9, sta: 11 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['warrior', 'paladin', 'shaman'],
  },
  thornbite_razor: {
    id: 'thornbite_razor',
    name: 'Thornbite Razor',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 20, max: 31, speed: 1.7, dagger: true },
    stats: { agi: 9, sta: 11 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['rogue', 'hunter', 'druid'],
  },
  heartwood_warstaff: {
    id: 'heartwood_warstaff',
    name: 'Heartwood Warstaff',
    kind: 'weapon',
    slot: 'mainhand',
    quality: 'epic',
    requiredLevel: 20,
    weapon: { min: 37, max: 54, speed: 3 },
    stats: { int: 9, sta: 7, spi: 4 },
    pvpOffenseRating: 20,
    pvpDefenseRating: 20,
    priceHonor: 800,
    sellValue: 0,
    soulbound: true,
    requiredClass: ['mage', 'priest', 'warlock', 'shaman', 'paladin', 'druid'],
  },
};

export const FURY_STOCK: readonly string[] = Object.keys(WARFARE_ITEMS);

export const FURY_NPC: NpcDef = {
  id: FURY_NPC_ID,
  name: 'Bramble',
  title: 'Honor Quartermaster',
  pos: { x: -11, z: -6 },
  facing: Math.PI / 2,
  color: 0xb52a2a,
  questIds: [],
  vendorItems: [...FURY_STOCK],
  dynamic: true,
  greeting: 'The sands remember every victory. Spend your honor well.',
};
