// GENERATED by scripts/wiki/build_content.mjs from src/sim/content. Do not edit by hand.
// Regenerate with `npm run wiki:content`; tests/guide.test.ts checks it stays fresh.
// Spec names and ability names are the English sim source (proper nouns); all other
// Guide copy is localized via guide.* t() keys.

export type GuideRole = 'tank' | 'healer' | 'dps';
export type GuideResource = 'rage' | 'mana' | 'energy';

export interface GuideClassSpec { name: string; role: GuideRole; }
export interface GuideSignatureAbility { id: string; name: string; }

export interface GuideClassInfo {
  id: string;
  color: string;
  resource: GuideResource;
  roles: GuideRole[];
  specs: GuideClassSpec[];
  signatureAbilities: GuideSignatureAbility[];
}

export interface GuideZoneInfo {
  id: string;
  name: string;
  min: number;
  max: number;
  biome: string;
  hub: string;
}

export interface GuideCreature { name: string; min: number; max: number; rare: boolean; }
export interface GuideFamily { family: string; creatures: GuideCreature[]; }

export const GUIDE_CLASSES: GuideClassInfo[] = [
  {
    "id": "warrior",
    "color": "#c79c6e",
    "resource": "rage",
    "roles": [
      "tank",
      "dps"
    ],
    "specs": [
      {
        "name": "Arms",
        "role": "dps"
      },
      {
        "name": "Fury",
        "role": "dps"
      },
      {
        "name": "Protection",
        "role": "tank"
      }
    ],
    "signatureAbilities": [
      {
        "id": "heroic_strike",
        "name": "Heroic Strike"
      },
      {
        "id": "battle_shout",
        "name": "Battle Shout"
      },
      {
        "id": "commanding_shout",
        "name": "Commanding Shout"
      },
      {
        "id": "charge",
        "name": "Charge"
      },
      {
        "id": "rend",
        "name": "Rend"
      },
      {
        "id": "thunder_clap",
        "name": "Thunder Clap"
      }
    ]
  },
  {
    "id": "paladin",
    "color": "#f58cba",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Holy",
        "role": "healer"
      },
      {
        "name": "Protection",
        "role": "tank"
      },
      {
        "name": "Retribution",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "seal_of_righteousness",
        "name": "Seal of Righteousness"
      },
      {
        "id": "holy_light",
        "name": "Holy Light"
      },
      {
        "id": "devotion_aura",
        "name": "Devotion Aura"
      },
      {
        "id": "judgement",
        "name": "Judgement"
      },
      {
        "id": "blessing_of_might",
        "name": "Blessing of Might"
      },
      {
        "id": "divine_protection",
        "name": "Divine Protection"
      }
    ]
  },
  {
    "id": "hunter",
    "color": "#abd473",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Beast Mastery",
        "role": "dps"
      },
      {
        "name": "Marksmanship",
        "role": "dps"
      },
      {
        "name": "Survival",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "raptor_strike",
        "name": "Raptor Strike"
      },
      {
        "id": "aspect_of_the_hawk",
        "name": "Aspect of the Hawk"
      },
      {
        "id": "serpent_sting",
        "name": "Serpent Sting"
      },
      {
        "id": "arcane_shot",
        "name": "Arcane Shot"
      },
      {
        "id": "concussive_shot",
        "name": "Concussive Shot"
      },
      {
        "id": "mongoose_bite",
        "name": "Mongoose Bite"
      }
    ]
  },
  {
    "id": "rogue",
    "color": "#fff569",
    "resource": "energy",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Assassination",
        "role": "dps"
      },
      {
        "name": "Combat",
        "role": "dps"
      },
      {
        "name": "Subtlety",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "sinister_strike",
        "name": "Sinister Strike"
      },
      {
        "id": "eviscerate",
        "name": "Eviscerate"
      },
      {
        "id": "garrote",
        "name": "Garrote"
      },
      {
        "id": "backstab",
        "name": "Backstab"
      },
      {
        "id": "gouge",
        "name": "Gouge"
      },
      {
        "id": "cheap_shot",
        "name": "Cheap Shot"
      }
    ]
  },
  {
    "id": "priest",
    "color": "#fffff0",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Discipline",
        "role": "healer"
      },
      {
        "name": "Holy",
        "role": "healer"
      },
      {
        "name": "Shadow",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "smite",
        "name": "Smite"
      },
      {
        "id": "lesser_heal",
        "name": "Lesser Heal"
      },
      {
        "id": "power_word_fortitude",
        "name": "Power Word: Fortitude"
      },
      {
        "id": "shadow_word_pain",
        "name": "Shadow Word: Pain"
      },
      {
        "id": "power_word_shield",
        "name": "Power Word: Shield"
      },
      {
        "id": "renew",
        "name": "Renew"
      }
    ]
  },
  {
    "id": "shaman",
    "color": "#0070de",
    "resource": "mana",
    "roles": [
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Elemental",
        "role": "dps"
      },
      {
        "name": "Enhancement",
        "role": "dps"
      },
      {
        "name": "Restoration",
        "role": "healer"
      }
    ],
    "signatureAbilities": [
      {
        "id": "lightning_bolt",
        "name": "Lightning Bolt"
      },
      {
        "id": "rockbiter_weapon",
        "name": "Rockbiter Weapon"
      },
      {
        "id": "healing_wave",
        "name": "Healing Wave"
      },
      {
        "id": "earth_shock",
        "name": "Earth Shock"
      },
      {
        "id": "lightning_shield",
        "name": "Lightning Shield"
      },
      {
        "id": "flame_shock",
        "name": "Flame Shock"
      }
    ]
  },
  {
    "id": "mage",
    "color": "#69ccf0",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Arcane",
        "role": "dps"
      },
      {
        "name": "Fire",
        "role": "dps"
      },
      {
        "name": "Frost",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "fireball",
        "name": "Fireball"
      },
      {
        "id": "frost_armor",
        "name": "Frost Armor"
      },
      {
        "id": "arcane_intellect",
        "name": "Arcane Intellect"
      },
      {
        "id": "frostbolt",
        "name": "Frostbolt"
      },
      {
        "id": "conjure_water",
        "name": "Conjure Water"
      },
      {
        "id": "conjure_food",
        "name": "Conjure Food"
      }
    ]
  },
  {
    "id": "warlock",
    "color": "#9482c9",
    "resource": "mana",
    "roles": [
      "dps"
    ],
    "specs": [
      {
        "name": "Affliction",
        "role": "dps"
      },
      {
        "name": "Demonology",
        "role": "dps"
      },
      {
        "name": "Destruction",
        "role": "dps"
      }
    ],
    "signatureAbilities": [
      {
        "id": "shadow_bolt",
        "name": "Shadow Bolt"
      },
      {
        "id": "summon_imp",
        "name": "Summon Imp"
      },
      {
        "id": "demon_skin",
        "name": "Demon Skin"
      },
      {
        "id": "immolate",
        "name": "Immolate"
      },
      {
        "id": "corruption",
        "name": "Corruption"
      },
      {
        "id": "life_tap",
        "name": "Life Tap"
      }
    ]
  },
  {
    "id": "druid",
    "color": "#ff7d0a",
    "resource": "mana",
    "roles": [
      "tank",
      "healer",
      "dps"
    ],
    "specs": [
      {
        "name": "Balance",
        "role": "dps"
      },
      {
        "name": "Feral",
        "role": "tank"
      },
      {
        "name": "Restoration",
        "role": "healer"
      }
    ],
    "signatureAbilities": [
      {
        "id": "wrath",
        "name": "Wrath"
      },
      {
        "id": "healing_touch",
        "name": "Healing Touch"
      },
      {
        "id": "mark_of_the_wild",
        "name": "Mark of the Wild"
      },
      {
        "id": "moonfire",
        "name": "Moonfire"
      },
      {
        "id": "rejuvenation",
        "name": "Rejuvenation"
      },
      {
        "id": "thorns",
        "name": "Thorns"
      }
    ]
  }
];

export const GUIDE_ZONES: GuideZoneInfo[] = [
  {
    "id": "eastbrook_vale",
    "name": "Eastbrook Vale",
    "min": 1,
    "max": 7,
    "biome": "vale",
    "hub": "Eastbrook"
  },
  {
    "id": "mirefen_marsh",
    "name": "Mirefen Marsh",
    "min": 6,
    "max": 13,
    "biome": "marsh",
    "hub": "Fenbridge"
  },
  {
    "id": "thornpeak_heights",
    "name": "Thornpeak Heights",
    "min": 13,
    "max": 20,
    "biome": "peaks",
    "hub": "Highwatch"
  }
];

export const GUIDE_FAMILIES: GuideFamily[] = [
  {
    "family": "beast",
    "creatures": [
      {
        "name": "Brightwood Hare",
        "min": 1,
        "max": 2,
        "rare": false
      },
      {
        "name": "Forest Wolf",
        "min": 1,
        "max": 2,
        "rare": false
      },
      {
        "name": "Glade Fox",
        "min": 2,
        "max": 3,
        "rare": false
      },
      {
        "name": "Spotted Fawn",
        "min": 2,
        "max": 3,
        "rare": false
      },
      {
        "name": "Wild Boar",
        "min": 2,
        "max": 3,
        "rare": false
      },
      {
        "name": "Dawnmane Doe",
        "min": 3,
        "max": 4,
        "rare": false
      },
      {
        "name": "Meadow Crane",
        "min": 3,
        "max": 4,
        "rare": false
      },
      {
        "name": "Thornpelt Badger",
        "min": 3,
        "max": 4,
        "rare": false
      },
      {
        "name": "Bramble Lynx",
        "min": 4,
        "max": 5,
        "rare": false
      },
      {
        "name": "Brightwood Stag",
        "min": 4,
        "max": 5,
        "rare": false
      },
      {
        "name": "Old Greyjaw",
        "min": 4,
        "max": 4,
        "rare": true
      },
      {
        "name": "Grovetusk Boar",
        "min": 5,
        "max": 6,
        "rare": false
      },
      {
        "name": "Sunhide Bear",
        "min": 5,
        "max": 6,
        "rare": false
      },
      {
        "name": "Mire Prowler",
        "min": 7,
        "max": 8,
        "rare": false
      },
      {
        "name": "Bog Bloat",
        "min": 9,
        "max": 11,
        "rare": false
      },
      {
        "name": "Ridge Stalker",
        "min": 13,
        "max": 14,
        "rare": false
      }
    ]
  },
  {
    "family": "spider",
    "creatures": [
      {
        "name": "Webwood Lurker",
        "min": 2,
        "max": 4,
        "rare": false
      },
      {
        "name": "Sableweb Hatchling",
        "min": 5,
        "max": 5,
        "rare": false
      },
      {
        "name": "Mirefen Widow",
        "min": 8,
        "max": 10,
        "rare": false
      }
    ]
  },
  {
    "family": "murloc",
    "creatures": [
      {
        "name": "Mudfin Skulker",
        "min": 3,
        "max": 5,
        "rare": false
      },
      {
        "name": "Deepfen Snapper",
        "min": 8,
        "max": 9,
        "rare": false
      },
      {
        "name": "Mirejaw Frenzy",
        "min": 9,
        "max": 10,
        "rare": false
      }
    ]
  },
  {
    "family": "kobold",
    "creatures": [
      {
        "name": "Tunnel Rat Digger",
        "min": 4,
        "max": 6,
        "rare": false
      },
      {
        "name": "Deeprock Tunneler",
        "min": 14,
        "max": 15,
        "rare": false
      },
      {
        "name": "Ironvein Sapper",
        "min": 15,
        "max": 16,
        "rare": false
      }
    ]
  },
  {
    "family": "humanoid",
    "creatures": [
      {
        "name": "Vale Bandit",
        "min": 3,
        "max": 5,
        "rare": false
      },
      {
        "name": "Mogger Lackey",
        "min": 5,
        "max": 6,
        "rare": false
      },
      {
        "name": "Gravecaller Cultist",
        "min": 10,
        "max": 12,
        "rare": false
      },
      {
        "name": "Gravecaller Mender",
        "min": 11,
        "max": 12,
        "rare": false
      },
      {
        "name": "Gravecaller Summoner",
        "min": 11,
        "max": 12,
        "rare": false
      },
      {
        "name": "Nhalia Mourner",
        "min": 11,
        "max": 12,
        "rare": false
      },
      {
        "name": "Wyrmcult Zealot",
        "min": 17,
        "max": 19,
        "rare": false
      },
      {
        "name": "Wyrmcult Necromancer",
        "min": 18,
        "max": 19,
        "rare": false
      }
    ]
  },
  {
    "family": "troll",
    "creatures": [
      {
        "name": "Mirefen Troll",
        "min": 10,
        "max": 12,
        "rare": false
      },
      {
        "name": "Grubjaw the Glutton",
        "min": 12,
        "max": 12,
        "rare": true
      }
    ]
  },
  {
    "family": "ogre",
    "creatures": [
      {
        "name": "Thornpeak Ogre",
        "min": 15,
        "max": 16,
        "rare": false
      }
    ]
  },
  {
    "family": "undead",
    "creatures": [
      {
        "name": "Restless Bones",
        "min": 5,
        "max": 7,
        "rare": false
      },
      {
        "name": "Drowned Dead",
        "min": 9,
        "max": 11,
        "rare": false
      },
      {
        "name": "Boneclad Revenant",
        "min": 18,
        "max": 19,
        "rare": false
      },
      {
        "name": "Varkas Boneguard",
        "min": 18,
        "max": 19,
        "rare": false
      }
    ]
  },
  {
    "family": "elemental",
    "creatures": [
      {
        "name": "Stormcrag Elemental",
        "min": 17,
        "max": 18,
        "rare": false
      },
      {
        "name": "Shardlord Kazzix",
        "min": 18,
        "max": 18,
        "rare": true
      }
    ]
  }
];
